// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TaxCalculationsAPI.Models;

public partial class Db_TaxCalculationContext : DbContext
{
    public Db_TaxCalculationContext(DbContextOptions<Db_TaxCalculationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<PostalCode> PostalCodes { get; set; }

    public virtual DbSet<ProgressiveTax> ProgressiveTaxes { get; set; }

    public virtual DbSet<TaxCalculatorResult> TaxCalculatorResults { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07CDACC2BA");

            entity.ToTable("Employee");

            entity.Property(e => e.Department)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Position)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.StartDate)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PostalCode>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PostalCo__3214EC07556CF128");

            entity.Property(e => e.PostalCode1)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("PostalCode");
            entity.Property(e => e.TaxCalculationType)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ProgressiveTax>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Progress__3214EC07538046E3");

            entity.ToTable("ProgressiveTax");
        });

        modelBuilder.Entity<TaxCalculatorResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaxCalcu__3214EC0777651D0D");

            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.PostalCode)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}