// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaxCalculationsAPI.Models;

public partial class PostalCode
{
    public int Id { get; set; }

    public string PostalCode1 { get; set; }

    public string TaxCalculationType { get; set; }
}