// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaxCalculationsAPI.Models;

public partial class ProgressiveTax
{
    public int Id { get; set; }

    public int? Rate { get; set; }

    public double? FromAmount { get; set; }

    public double? ToAmount { get; set; }
}